environment:
  matrix:
    - ANDROID_HOME: "C:\\android-sdk-windows"
install:
  - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-3859397.zip
  - appveyor DownloadFile https://dl.google.com/android/repository/android-ndk-r19c-windows-x86_64.zip
  - 7z x sdk-tools-windows-3859397.zip -oC:\android-sdk-windows > nul
  - 7z x android-ndk-r19c-windows-x86_64.zip -oC:\android-ndk-windows > nul
  - yes | C:\android-sdk-windows\tools\bin\sdkmanager.bat --licenses
build_script:
  - gradlew.bat assemble
artifacts:
  - path: app/build/outputs/apk/debug/app-debug.apk
